version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  zookeeper:
    image: zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  feed:
    build: ./newsfeed_service
    ports:
      - "5001:5001"
    depends_on:
      redis:
        condition: service_healthy

  post:
    build: ./post_service
    ports:
      - "4001:4001"
    depends_on:
      redis:
        condition: service_healthy

  notification:
    build: ./notification_service
    ports:
      - "8002:8002"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy

  registration:
    build: ./registration_service
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
