version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  feed:
    build: ./newsfeed_service
    ports:
      - "5001:5001"
    depends_on:
      - redis

  post:
    build: ./post_service
    ports:
      - "4001:4001"
    depends_on:
      - redis

  notification:
    build: ./notification_service
    ports:
      - "8002:8002"
    depends_on:
      - kafka
      - redis

  registration:
    build: ./registration_service
    ports:
      - "3001:3001"
    depends_on:
      - redis
